

import './globals.css';
import { fonts } from './fonts';

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fonts.geistSans.variable} ${fonts.geistMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}

// 使用方式：
// `${fonts.GeistSans.variable} ${fonts.GeistMono.variable}`

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
